# Generated by Django 4.2.7 on 2023-11-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticepost',
            old_name='head_image',
            new_name='notice_image',
        ),
    ]
