# Generated by Django 4.2.7 on 2023-11-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_rename_head_image_noticepost_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticepost',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
    ]
