# Generated by Django 4.2.7 on 2023-11-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_noticepost_is_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticepost',
            old_name='is_pin',
            new_name='top_fixed',
        ),
    ]
