# Generated by Django 4.2.7 on 2023-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_rename_is_pin_noticepost_top_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticepost',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
