# Generated by Django 4.2.7 on 2023-11-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_noticepost_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticepost',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
