# Generated by Django 4.2.7 on 2023-11-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpost',
            name='location',
            field=models.CharField(blank=True, choices=[('정문', '정문'), ('후문', '후문'), ('인문사회관', '인문사회관'), ('대강의동', '대강의동'), ('차마리사관', '차미리사관'), ('학생회관', '학생회관'), ('도서관', '도서관'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
