# Generated by Django 4.2.7 on 2023-11-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_alter_lostpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpost',
            name='found_status',
            field=models.CharField(choices=[('찾음', '찾음'), ('못찾음', '못찾음')], default='못찾음', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostpost',
            name='location',
            field=models.CharField(blank=True, choices=[('정문·대학본부', '정문·대학본부'), ('후문', '후문'), ('인문사회관', '인문사회관'), ('대강의동', '대강의동'), ('차마리사기념관', '차미리사기념관'), ('학생회관', '학생회관'), ('도서관·대학원', '도서관·대학원'), ('예술관', '예술관'), ('자연관', '자연관'), ('약학관', '약학관'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
