# Generated by Django 4.2.7 on 2023-11-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
