# Generated by Django 4.2.7 on 2023-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0007_rename_content_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
