# Generated by Django 4.2.7 on 2023-11-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0008_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
