# Generated by Django 4.2.7 on 2023-11-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
