# Generated by Django 4.2.7 on 2023-11-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0018_board_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lost.lostpost'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
