# Generated by Django 4.2.7 on 2023-11-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0019_alter_comment_board_delete_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
