# Generated by Django 4.2.7 on 2023-11-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_rename_category_findcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
    ]
