# Generated by Django 4.2.7 on 2023-11-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0007_findlocation_post_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findlocation',
            options={'verbose_name_plural': 'locations'},
        ),
    ]
