# Generated by Django 4.2.7 on 2023-11-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0008_alter_findlocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_select',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
