# Generated by Django 4.2.7 on 2023-11-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0009_post_date_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FindComment',
        ),
    ]
