# Generated by Django 4.2.7 on 2023-11-23 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find', '0010_findcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='findcomment',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='findcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='find.findcomment'),
        ),
        migrations.AlterField(
            model_name='findcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='find.post'),
        ),
    ]
