# Generated by Django 4.2.7 on 2023-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0011_alter_findcomment_author_alter_findcomment_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FindComment',
        ),
    ]
