# Generated by Django 4.2.7 on 2023-11-28 01:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find', '0011_remove_post_category_remove_post_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FindPost',
        ),
    ]
