# Generated by Django 4.2.7 on 2023-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0012_rename_post_findpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpost',
            name='category',
            field=models.CharField(blank=True, choices=[('전자기기', '전자기기'), ('지갑/카드', '지갑/카드'), ('악세사리', '악세사리'), ('화장품', '화장품'), ('기타', '기타')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='findpost',
            name='location',
            field=models.CharField(blank=True, choices=[('정문·대학본부', '정문·대학본부'), ('후문', '후문'), ('인문사회관', '인문사회관'), ('대강의동', '대강의동'), ('차마리사기념관', '차미리사기념관'), ('학생회관', '학생회관'), ('도서관·대학원', '도서관·대학원'), ('예술관', '예술관'), ('자연관', '자연관'), ('약학관', '약학관'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
